apiVersion: apps/v1
kind: Deployment
metadata:
 name: java-application
spec:
 replicas: 1
 strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0  
 selector:
   matchLabels:
     app: java-application
 template:
   metadata:
     labels:
       app: java-application
   spec:
    containers:
    - name: java-application
      image: huynguyenquang116/be_application:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8082

---       
apiVersion: v1
kind: Service
metadata:
  name: java-backend
spec:
  selector:
    app: java-application 
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
 
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
name: be-route
spec:
to:
  kind: Service
  name: java-backend
port:
  targetPort: http
tls:
  termination: edge
wildcardPolicy: None